import type { NextPage } from "next";
import Head from "next/head";

type HeadSEOType = {
  text: string;
};

const HeadSEO: NextPage<HeadSEOType> = ({ text }) => {
  return (
    <Head>
      <title>{text}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HeadSEO;
